apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-cluster-shivam01
  
---

apiVersion: v1
kind: Service
metadata: 
  name: nodeportservice-develop
  namespace: kubernetes-cluster-shivam01
  labels: 
    service: nodeport
spec:
  type: NodePort 
  ports:
    - port: 7300
      targetPort: 7300
      nodePort: 30158
  selector:
      app: WebAppDevelop

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: shivam01-webapp-deployment-d
  namespace: kubernetes-cluster-shivam01
  labels:
    app: WebAppDevelop
spec:
  template:
    metadata:
      name: shivam01-webapp-pod-d
      namespace: kubernetes-cluster-shivam01
      labels:
        app: WebAppDevelop
    spec:
      containers:
      - name: shivam01-webapp-container-d
        image: shivamsahni/basicmath:latest
        ports:
          - containerPort: 7300        
  replicas: 4
  selector:
    matchLabels:
      app: WebAppDevelop



    
